openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs - Steps
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}/steps/{stepId}:
    get:
      tags:
        - Job - Step
      summary: Get a single Job Step
      operationId: jobStepGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - $ref: './jobStep.yaml#/components/parameters/stepId'
      responses:
        200:
          description: The details of the desired Job Step
          content:
            application/json:
              schema:
                $ref: './jobStep.yaml#/components/schemas/jobStep'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
